### ISSUE TITLE
Error occurred while enabling WolfyUtilities v1.5.0.0

### ISSUE THREAD

**Issue by andris155** [WolfyScript/WolfyUtilities#1]
```
[03:59:06] [Server thread/INFO]: [WolfyUtilities] Enabling WolfyUtilities v1.5.0.0
[03:59:06] [Server thread/ERROR]: Error occurred while enabling WolfyUtilities v1.5.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sun/corba/se/impl/io/TypeMismatchException
	at me.wolfyscript.utilities.main.Main.onEnable(Main.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-31]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-31]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-31]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-31]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.corba.se.impl.io.TypeMismatchException
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.15.1.jar:git-Paper-31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 10 more
[03:59:06] [Server thread/INFO]: [WolfyUtilities] Disabling WolfyUtilities v1.5.0.0
```
Paper 1.15.1
Java 11.0.5

**Comment by Mrok71** [comment]
Same

07:03:14 INFO]: [WolfyUtilities] Loading WolfyUtilities v1.5.0.0
[07:03:14 ERROR]: [org.bukkit.craftbukkit.v1_15_R1.CraftServer] com/sun/corba/se/impl/io/TypeMismatchException initializing WolfyUtilities v1.5.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sun/corba/se/impl/io/TypeMismatchException
        at me.wolfyscript.utilities.api.utils.Legacy.initEnchants(Legacy.java:39) ~[?:?]
        at me.wolfyscript.utilities.api.utils.Legacy.init(Legacy.java:15) ~[?:?]
        at me.wolfyscript.utilities.main.Main.onLoad(Main.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:361) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-33]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.corba.se.impl.io.TypeMismatchException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.15.1.jar:git-Paper-33]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 7 more

**Comment by WolfyScript** [comment]
Please try the latest update. It should fix it. If it doesn't you need to downgrade your Java to Java 8

**Comment by WolfyScript** [comment]
Alright, I think I got it. I cannot promise it will fix it, because it's an incompatibility error with the latest Java versions. I'm going to upload an update today to test it out.

**Comment by WolfyScript** [comment]
Does the new update fixes it?

**Comment by andris155** [comment]
Fixed. Thanks!
