### ISSUE TITLE
Can not set final int field

### ISSUE THREAD

**Issue by LupusVirtute** [WolfyScript/WolfyUtilities#110]
**Describe the bug**
java.lang.IllegalArgumentException

**To Reproduce**
1. /recipes
2. -> Error

**Expected behavior**
Not receiving this Exception in console

**Screenshots**

**Server (please complete the following information):**
 - Server Software: Paper
 - Minecraft version 1.19.4
 - Java version 17

**Additional context**
Logs: 
```
[13:52:00 INFO]: Sfiksowany issued server command: /recipes
[13:52:04 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Integer
[13:52:04 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[13:52:04 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[13:52:04 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[13:52:04 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[13:52:04 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[13:52:04 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[13:52:04 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.util.reflection.InventoryUpdate.updateInventory(InventoryUpdate.java:134)
[13:52:04 WARN]:        at customcrafting-spigot-4.16.6.0.jar//me.wolfyscript.customcrafting.gui.recipebook.MenuRecipeOverview.onUpdateAsync(MenuRecipeOverview.java:164)
[13:52:04 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.openInventory(GuiWindow.java:282)
[13:52:04 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$callUpdate$1(GuiWindow.java:272)
[13:52:04 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.callUpdate(GuiWindow.java:274)
[13:52:04 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$update$0(GuiWindow.java:265)
[13:52:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[13:52:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:52:04 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1510)
[13:52:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[13:52:04 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[13:52:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
[13:52:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[13:52:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:52:07 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Integer
[13:52:07 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[13:52:07 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[13:52:07 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[13:52:07 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[13:52:07 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[13:52:07 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[13:52:07 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.util.reflection.InventoryUpdate.updateInventory(InventoryUpdate.java:134)
[13:52:07 WARN]:        at customcrafting-spigot-4.16.6.0.jar//me.wolfyscript.customcrafting.gui.recipebook.MenuRecipeOverview.onUpdateAsync(MenuRecipeOverview.java:164)
[13:52:07 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.openInventory(GuiWindow.java:282)
[13:52:07 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$callUpdate$1(GuiWindow.java:272)
[13:52:07 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.callUpdate(GuiWindow.java:274)
[13:52:07 WARN]:        at wolfyutils-spigot-4.16.10.1.jar//me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$update$0(GuiWindow.java:265)
[13:52:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[13:52:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:52:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1510)
[13:52:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[13:52:07 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[13:52:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
[13:52:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[13:52:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by WolfyScript** [comment]
Looks like I forgot to upload the update that fixes this to CurseForge. Going to do that now.

You can find the download for v4.16.10.2 here on GitHub https://github.com/WolfyScript/WolfyUtils-Spigot/releases
