### ISSUE TITLE
1.20.2 Not support in lastest version

### ISSUE THREAD

**Issue by addpromax** [WolfyScript/WolfyUtilities#114]
**Describe the bug**
detect nms fail

**To Reproduce**
1. install
2. error

**Expected behavior**
No error

**Screenshots**
[23:04:02] [Server thread/INFO]: [WolfyUtilities] NMS Version: v1_20_R2
[23:04:02] [Server thread/WARN]: java.lang.ClassNotFoundException: me.wolfyscript.utilities.api.nms.v1_20_R2.NMSEntry
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:383)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:376)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.nms.NMSUtil.create(NMSUtil.java:89)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//com.wolfyscript.utilities.bukkit.WolfyUtilsBukkit.<init>(WolfyUtilsBukkit.java:56)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilities.<init>(WolfyUtilities.java:69)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilities.<init>(WolfyUtilities.java:77)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilCore.lambda$getAPI$0(WolfyUtilCore.java:533)
[23:04:02] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilCore.getAPI(WolfyUtilCore.java:533)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilCore.getAPI(WolfyUtilCore.java:520)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilCore.<init>(WolfyUtilCore.java:202)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//com.wolfyscript.utilities.paper.WolfyCorePaper.<init>(WolfyCorePaper.java:20)
[23:04:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:60)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[23:04:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528)
[23:04:02] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[23:04:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
[23:04:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:04:02] [Server thread/WARN]: [WolfyUtilities] Did not detect NMS implementation for server version (v1_20_R2)! Using Fallback! This might cause issue if plugins use the NMS Utils!
[23:04:02] [Server thread/INFO]: [me.wolfyscript.lib.org.reflections.Reflections] Reflections took 124 ms to scan 1 urls, producing 1266 keys and 4001 values
[23:04:02] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.crafting.CraftingManager.addRecipe(net.minecraft.world.item.crafting.IRecipe)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2259)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.util.Reflection.getMethod(Reflection.java:223)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.util.Reflection.getMethod(Reflection.java:205)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//com.wolfyscript.utilities.bukkit.nms.item.crafting.FunctionalRecipeGenerator.<clinit>(FunctionalRecipeGenerator.java:166)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//me.wolfyscript.utilities.api.WolfyUtilCore.<init>(WolfyUtilCore.java:211)
[23:04:02] [Server thread/WARN]: 	at wolfyutils-spigot-4.16.12.1.jar//com.wolfyscript.utilities.paper.WolfyCorePaper.<init>(WolfyCorePaper.java:20)
[23:04:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:60)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[23:04:02] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[23:04:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528)
[23:04:02] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[23:04:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
[23:04:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[23:04:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Server (please complete the following information):**
 - Server Software : purpur
 - Minecraft version : 1.20.2
 - Java version :17

**Additional context**

**Comment by addpromax** [comment]
beta version not this
