### ISSUE TITLE
The plugin crashes with an error StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Sauron971** [WolfyScript/WolfyUtilities#123]
When loading the plugin in the console, it returns an error
[14:38:08 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'wolfyutils-spigot-4.16.15.jar' in folder 'plugins'
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:60) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:522) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2181]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.nms.NMSUtil.create(NMSUtil.java:81) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/com.wolfyscript.utilities.bukkit.WolfyUtilsBukkit.<init>(WolfyUtilsBukkit.java:56) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilities.<init>(WolfyUtilities.java:69) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilities.<init>(WolfyUtilities.java:77) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.lambda$getAPI$0(WolfyUtilCore.java:541) ~[wolfyutils-spigot-4.16.15.jar:?]
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.getAPI(WolfyUtilCore.java:541) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.getAPI(WolfyUtilCore.java:528) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.<init>(WolfyUtilCore.java:204) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/com.wolfyscript.utilities.paper.WolfyCorePaper.<init>(WolfyCorePaper.java:20) ~[wolfyutils-spigot-4.16.15.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        ... 14 more
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.util.Reflection.getVersion(Reflection.java:84) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.util.Reflection.<clinit>(Reflection.java:42) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.nms.NMSUtil.create(NMSUtil.java:81) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/com.wolfyscript.utilities.bukkit.WolfyUtilsBukkit.<init>(WolfyUtilsBukkit.java:56) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilities.<init>(WolfyUtilities.java:69) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilities.<init>(WolfyUtilities.java:77) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.lambda$getAPI$0(WolfyUtilCore.java:541) ~[wolfyutils-spigot-4.16.15.jar:?]
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.getAPI(WolfyUtilCore.java:541) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.getAPI(WolfyUtilCore.java:528) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/me.wolfyscript.utilities.api.WolfyUtilCore.<init>(WolfyUtilCore.java:204) ~[wolfyutils-spigot-4.16.15.jar:?]
        at wolfyutils-spigot-4.16.15.jar/com.wolfyscript.utilities.paper.WolfyCorePaper.<init>(WolfyCorePaper.java:20) ~[wolfyutils-spigot-4.16.15.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        ... 14 more
Along with that, customcrafting just doesn't load.

**Server (please complete the following information):**
 - Server Software Purpur
 - Minecraft version 1.20.6
 - Java version 21

**Comment by DuneSciFye** [comment]
Also having this issue on 1.21 AdvancedSlimePaper
