### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by LautjeDS** [WolfyScript/WolfyUtilities#28]
When the server starts, the plugin disables with the following error message:

`[07:21:09 ERROR]: Error occurred while enabling WolfyUtilities v1.6.4.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.wolfyscript.utilities.util.world.WorldCustomItemStore.initiateMissingBlockEffects()" because the return value of "me.wolfyscript.utilities.util.world.WorldUtils.getWorldCustomItemStore()" is null
        at me.wolfyscript.utilities.main.WUPlugin.loadParticleEffects(WUPlugin.java:179) ~[?:?]
        at me.wolfyscript.utilities.main.WUPlugin.onEnable(WUPlugin.java:157) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:949) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.Bukkit.reload(Bukkit.java:726) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-650]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-650]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:453) ~[patched_1.16.5.jar:git-Paper-650]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.16.5.jar:git-Paper-650]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-650]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-650]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-650]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by srnyx** [comment]
This is happening to me, it happened after I updated.

**Comment by WolfyScript** [comment]
Try to delete the WolfyUtilities/world_custom_item.store file.
I am still unsure why it happens.

**Comment by srnyx** [comment]
> Try to delete the WolfyUtilities/world_custom_item.store file.
> I am still unsure why it happens.

Works now, thanks
