### ISSUE TITLE
it wont start

### ISSUE THREAD

**Issue by PlebexerMC** [WolfyScript/WolfyUtilities#38]
i updated wolfy utilities and it wont start

```
[23:42:19] [Server thread/ERROR]: Fatal error trying to convert WolfyUtilities v1.7.2.0:me/wolfyscript/utilities/main/WUPlugin.class
java.lang.IllegalArgumentException: Unsupported class file major version 60
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.util.Commodore.convert(Commodore.java:171) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:299) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_272]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_272]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_272]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[23:42:19] [Server thread/ERROR]: Could not load 'plugins/wolfyutilities-1.7.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/wolfyscript/utilities/main/WUPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.UnsupportedClassVersionError: me/wolfyscript/utilities/main/WUPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_272]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_272]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_272]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_272]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_272]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_272]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-391]
	... 6 more
[23:42:19] [Server thread/ERROR]: Could not load 'plugins/customcrafting-1.6.6.0.1f.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency WolfyUtilities. Please download and install WolfyUtilities to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

**Server (please complete the following information):**
 - Server Software: Paper
 - Minecraft version: 1.15.2
 - Java version: Java 8

**Comment by PlebexerMC** [comment]
i just realised the plugin only uses java 16 now, sorry

**Comment by WolfyScript** [comment]
If you still wanna use it on Java 8 you can use WolfyUtilities 1.6.4.2, which is compatible with CustomCrafting 1.6.6.0.1 and supports Java 8.
