### ISSUE TITLE
Is it currupted currently

### ISSUE THREAD

**Issue by Killian225** [WolfyScript/WolfyUtilities#91]
yes ik this may sound stupid but I think 4.16.1 of this plugin is currupted, i would install it and it says to install it with the custom recipes when i have installed it, so i decided to double click the jar file, and gives me the error invalid or currupt file when its supposed to do nothing and or install in some cases, java 16 is also installed, do u think u can fix this issue??

Could not load 'plugins\customcrafting-spigot-3.16.3.3.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency WolfyUtilities. Please download and install WolfyUtilities to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:268) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:386) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
remember it is installed

**Comment by natr566** [comment]
download and install WolfyUtilities
